export default [{
  id:'1',
  name:`夜曲`,
  title:`周杰伦`,
  img:`https://myhkw.cn/api/musicPic?picId=004cPHRr3nkmJe&type=qq&size=big`,
  audio:`https://github.com/yuanguandong/resources/blob/master/mp3/%E5%A4%9C%E6%9B%B2.mp3?raw=true`
},{
  id:'2',
  name:`夜空中最亮的星`,
  title:`逃跑计划`,
  img:`https://myhkw.cn/api/musicPic?picId=000wr4zc1gls3e&type=qq&size=big`,
  audio:`https://github.com/yuanguandong/resources/blob/master/mp3/%E5%A4%9C%E7%A9%BA%E4%B8%AD%E6%9C%80%E4%BA%AE%E7%9A%84%E6%98%9F.mp3?raw=true`
},{
  id:'3',
  name:`麻雀`,
  title:`李荣浩`,
  img:`https://myhkw.cn/api/musicPic?picId=003P3ByD1n8nBK&type=qq&size=big`,
  audio:`https://github.com/yuanguandong/resources/blob/master/mp3/%E9%BA%BB%E9%9B%80.mp3?raw=true`
},{
  id:'4',
  name:`红颜`,
  title:`胡彦斌`,
  img:`https://myhkw.cn/api/musicPic?picId=003f2csz26yPNf&type=qq&size=big`,
  audio:`https://github.com/yuanguandong/resources/blob/master/mp3/%E7%BA%A2%E9%A2%9C.mp3?raw=true`
},{
  id:'5',
  name:`光辉岁月`,
  title:`Beyond`,
  img:`https://myhkw.cn/api/musicPic?picId=000Oexke1G6Idv&type=qq&size=big`,
  audio:`https://github.com/yuanguandong/resources/blob/master/mp3/%E5%85%89%E8%BE%89%E5%B2%81%E6%9C%88.mp3?raw=true`
},{
  id:'6',
  name:`皇帝`,
  title:`胡彦斌`,
  img:`https://myhkw.cn/api/musicPic?picId=001113yq0FzW3O&type=qq&size=big`,
  audio:`https://github.com/yuanguandong/resources/blob/master/mp3/%E7%9A%87%E5%B8%9D.mp3?raw=true`
},{
  id:'7',
  name:`情人节`,
  title:`黄淑慧`,
  img:`https://myhkw.cn/api/musicPic?picId=ac940d4325ba7d34815afe8248820edc&type=kg&size=big`,
  audio:`https://github.com/yuanguandong/resources/blob/master/mp3/%E6%83%85%E4%BA%BA%E8%8A%82.mp3?raw=true`
},{
  id:'8',
  name:`祝你快乐`,
  title:`黄淑慧`,
  img:`https://myhkw.cn/api/musicPic?picId=ac940d4325ba7d34815afe8248820edc&type=kg&size=big`,
  audio:`https://github.com/yuanguandong/resources/blob/master/mp3/%E7%A5%9D%E4%BD%A0%E5%BF%AB%E4%B9%90.mp3?raw=true`
}]